# Generated by Django 4.1.3 on 2023-03-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities_to_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Countries_to_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='University_to_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uni_Name', models.CharField(max_length=250)),
                ('Uni_Acronym', models.CharField(max_length=250)),
                ('Uni_Logo', models.FileField(upload_to='')),
                ('Uni_Type', models.CharField(max_length=200)),
                ('Uni_Overview', models.TextField()),
                ('Uni_EstablishedYear', models.PositiveSmallIntegerField()),
                ('Uni_All_Students', models.PositiveIntegerField()),
                ('Uni_International_Students', models.PositiveIntegerField()),
                ('Uni_Website', models.URLField()),
                ('Uni_ApplyRate', models.FloatField()),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scorize_UniList.cities_to_apply')),
            ],
        ),
        migrations.AddField(
            model_name='cities_to_apply',
            name='from_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scorize_UniList.countries_to_apply'),
        ),
    ]
